language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: develpeliculasurjc
  on:
    all_branch: true
  api_key:
    secure: rSWB0uMDDpBZfzNJqxEqBCj6r3RSr88gEO7a0BUJ/Ls8oGj1bhBoZ71J0oGEQxBaxRvyXfNPF2YqVn4wSxENqb+Ts9HVLdIJ11urqGSEN5CxTdanhJy2RogRwazr782lx1d9qS4ChjqKSGXYSmj6NOFJQ9shCGBmStvXM2C/CE4v3aIEW209QuFLKwGTvKYISwtPFlm7TE6Ci5d7x2xPkt2QRE+joAIyvOVa2m9zJe43aCJ8NfUIfjncsJoMf7TagBkJqVxcObJdlbgZ38mzM+Svegz2sW8xo1Vy26gQ1Q92Z1/BVqXtplFOjLcF2halZaYUkShRuXx5jMOF85ca82Rcduoz0EuI8n5a3fh8UBCd+1NfO2emjcJIauxW8JmgAiz96nzlzUJm/5bxnqQ4jJuGy+cRs2wzhW4THfrdU98wUdCCizQ8gm+RsU5OR5bbkQJYn5IKm3NsyQ+UWTHEZrrSQXJTxvYL2zP7/OH3Fsuuw6FIC9c6kbM48hV3T9WtNvzpG3fnHd+X+8+UQE3knkl/DY5Dn5Ki/Yy5C6lzHwdLzt/S9Tdirxnq8L+ALzRfG/xyHciK48Sx+hcuZXhwkiupdKRzVMlt07FkCAkEtqlptaNILX7974whIENJjz2qhqPCnIygLYKt6umfSgyTHimUCmfD48BAxw1If+CXAQU=
