language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: develpeliculasurjc
  api_key:
    secure: NE2a0x3Z12K8yd8D2z+qI/e4CeVf2HbWSi2qiQ7/zX/qTVKUYa3qRwwqbnSpKqT2rtjAl7sh9vDvsrkNJgcTJK/4i+N4ZWWOEEWUGGl4N8D8z68aV9+VpFKtFQ7ZfuWYy4qJ8lVpi9w9SiBUuoJfFCwQ6ZpwzzUgjVtMf3TigEZMPnTYPPWmcIo/W4FmSMKL8lntkvGKJe3cIFU1m5JDu8PPv2baby74c37VKrwr2yHlgu2YnEnhLK/tJNVvQh9RE0jiFotxX+3oxTVce+HNjan4eq6eFaMdLVdrVOn3GT7x+STu23dxrKu1VDhiGBo1mRkw5Ao0cg0qEu6LX58Ft6K+aZVKQen/X0wyrfbXB6x51HsjwqQ+FZeAakBEjWYoAhkevqcuZhRS0ZEJjGiiqmIDkfoRQdMMr2MfjovJcNhGvso+lNjiF3i9+qiJSreog5jKCvEOlU/WXk5xn6ORJhUvO7C9rHq0gIjDjti/mLSWOsKkTrnM/9sReSuYwbHGYAZ9XuejYDY6Qe8QyzvShMl5BeGvWQYPOGqppINMYQo82/moBMdgWbdVYE38zEoJT6+jAqwwZCCS1hTR7T87aCydqjq2vlxlm1gPA6hFd19aR9gqHVK9QGWkWgtPq9VC7rdKAV6c/kNUt5RPTvtnkH9gmNFD37WNOmdN98RZL4E=
