language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: peliculasurjc
  on:
    repo: DanielRiveraPaniagua/ProyectoFinal_ISI
    branch: master
  api_key:
    secure: mayuV1oq+eWPO5N7tZf8FGWdQ4un8AR/RtMdQ7eKkTpGqHgGK9QIO4SMbPwGsUXVxduKNKwML9nZXj4dVih/NzncpLHLmrCwi/mul7C2xICr69H3v4nz1grOWoy5Sq5EJqQENeZC4S/AheMjpqh/jrrJr9f0BBe2bft11eYw+tooY2q9pzXD1EcgjQ0mwAdq/LA8dvc1vGIMWdPyNt2zywgyFP/LrReBSdd7wM+t64vORu5hO04BzUgwgLD1cC58k+sZPrXMlij+Xv9ZHI/cC2fkHIf8P1u6aHnjPN09BPSzj+C58C8pbrZYhuE0Ox2NZQ/P7HsE1nz8GfVEeI5w0Jjc/NGH3sO3Mbdl7366bUPFLiOh270zibY80AvM+pv59HUpbtLhEV0/nE9/W2PNRUwLuXtQyia4U6WXlmZiK01teqASnli/Zts6MmtL1sEF+TxtTMhLmDFG9iGCSf45kgyIxo2X7SnHLBOulJ0mDE8M/1YrXv/4Tvt4yXGQ5nYPxTW4lf0MhEhTcnm9JbSb3lS+jt5OcoQ1wwUKiJ5+qGZvh93OUG/W4tQ4045muHsMDHseHSPUTMhUrcQOOzpOi6HiKg42uxECp3ySsTfII4It9WmRZv1yco1ha5FErK59CqtkSpoYM/5uuNyrhe+FdX7XkoClwmvc6IhM8PfOr6c=
